app = 'fly-health-check'
primary_region = 'cdg'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'fly-health-check.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 1

  [[http_service.checks]]
    interval = '5s'
    timeout = '1s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health_check'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
